//! Landing: your working tree is the last stop before a commit, and guvnor's
//! signature on that commit is only worth anything while the index still holds
//! the diff a reviewer read.

use guvnor::engine::combined;
use guvnor::engine::land::{commit_at, set_gate_at, stage_at, unstage_at, unstaged_edits_at};
use guvnor::state::{self, State, Status};
use guvnor::{digest, git, review};
use std::path::{Path, PathBuf};

/// A repo with a baseline commit and one reviewed, fully-approved run whose
/// patches add a test file and a source file. Patches are generated by git
/// itself — a hand-rolled one would only prove that the fixture is wrong.
fn fixture(name: &str) -> (PathBuf, String) {
    fixture_verdict(name, review::Decision::Approved)
}

fn fixture_verdict(name: &str, decision: review::Decision) -> (PathBuf, String) {
    let repo = std::env::temp_dir().join(format!("guvnor-land-{name}-{}", std::process::id()));
    std::fs::remove_dir_all(&repo).ok();
    std::fs::create_dir_all(&repo).unwrap();
    let git = |args: &[&str]| git::git(&repo, args).unwrap();
    // Its own identity, and no signing: a developer's global git config is
    // not this test's business (a real repo keeps its own — guvnor shells
    // out to `git commit` precisely so your settings apply), and a CI runner
    // has no identity to borrow.
    git::init_test_repo(&repo);
    // run artifacts live in the repo but are never part of it
    std::fs::create_dir_all(repo.join(".guvnor")).unwrap();
    std::fs::write(repo.join(".guvnor/.gitignore"), "runs/\nwt/\n").unwrap();
    std::fs::write(repo.join("README"), "hi\n").unwrap();
    git(&["add", "-A"]);
    git(&["commit", "-qm", "base"]);

    // two patches, cut from real staged files, then wound back
    let patch = |path: &str, body: &str| {
        let full = repo.join(path);
        std::fs::create_dir_all(full.parent().unwrap()).unwrap();
        std::fs::write(&full, body).unwrap();
        git(&["add", path]);
        let p = git::git(&repo, &["diff", "--cached"]).unwrap();
        git(&["reset", "-q"]);
        std::fs::remove_file(&full).unwrap();
        p
    };
    let tests_patch = patch("test/a.test.js", "test-ok\n");
    let impl_patch = patch("src/a.js", "impl-ok\n");

    let id = "20260101T000000-land";
    let run_dir = state::runs_root(&repo).join(id);
    std::fs::create_dir_all(&run_dir).unwrap();
    std::fs::write(run_dir.join("tests.patch"), &tests_patch).unwrap();
    std::fs::write(run_dir.join("impl.patch"), &impl_patch).unwrap();
    let combined = combined(&tests_patch, &impl_patch);
    let review = review::Review {
        verdict: review::Verdict {
            verdict: decision,
            summary: "fine".into(),
            findings: vec![],
        },
        diff_sha256: digest::sha256_hex(combined.as_bytes()),
        model: "m".into(),
        ts: "now".into(),
    };
    std::fs::write(run_dir.join("review.json"), serde_json::to_string(&review).unwrap())
        .unwrap();
    // Approved the way set_gate approves: a tick plus a digest of the bytes
    // that were on screen.
    let mut st = State::new(id, "landing");
    st.gates.spec.approved = true;
    for (gate, patch) in [(state::Gate::Tests, &tests_patch), (state::Gate::Work, &impl_patch)] {
        let a = st.gates.slot_mut(gate);
        a.approved = true;
        a.sha256 = digest::sha256_hex(patch.as_bytes());
    }
    st.status = Status::Reviewed;
    st.save(&run_dir).unwrap();

    assert_eq!(
        git::git(&repo, &["status", "--porcelain"]).unwrap().trim(),
        "",
        "fixture must start clean or the staging checks are untested"
    );
    (repo, id.to_string())
}

fn status(repo: &Path, id: &str) -> Status {
    State::load(&state::resolve_run_dir(repo, id).unwrap()).unwrap().status
}

/// The reviewer holds no gate. The human's judgement is the work gate, made
/// with the verdict on the screen next to it; the check that carries the
/// weight is the diff digest.
#[test]
fn the_verdict_does_not_gate_landing() {
    for d in [review::Decision::Warning, review::Decision::Blocked] {
        let (repo, id) = fixture_verdict(&format!("verdict-{d}"), d);
        assert!(stage_at(&repo, &id).is_ok(), "{d} must be landable");
        assert_eq!(status(&repo, &id), Status::Staged);
        std::fs::remove_dir_all(&repo).ok();
    }
    // ...but a diff that is not the reviewed one still cannot land, whatever
    // the verdict said. That is the check that carries the weight.
    let (repo, id) = fixture_verdict("verdict-tamper", review::Decision::Approved);
    let run_dir = state::resolve_run_dir(&repo, &id).unwrap();
    std::fs::write(run_dir.join("impl.patch"), "tampered\n").unwrap();
    let e = stage_at(&repo, &id).unwrap_err().to_string();
    assert!(e.contains("impl.patch is not what the work gate approved"), "{e}");
    std::fs::remove_dir_all(&repo).ok();
}

/// A gate records a human's decision about content; it does not get to say
/// where the run is in its life. Overwriting `Staged` used to leave guvnor's
/// own patches sitting in the tree with `unstage` refusing to own them
/// ("nothing staged for this run"), recoverable only with `git reset`.
#[test]
fn a_gate_decision_does_not_rewrite_a_landed_status() {
    let (repo, id) = fixture("gate-vs-status");
    let run_dir = state::resolve_run_dir(&repo, &id).unwrap();
    stage_at(&repo, &id).unwrap();
    assert_eq!(status(&repo, &id), Status::Staged);
    // spec.json has to exist and parse for an approval to bind to it
    let sp = guvnor::spec::Spec {
        title: "t".into(),
        objective: "o".into(),
        files: vec!["src/a.js".into()],
        interfaces: vec!["f()".into()],
        constraints: vec![],
        verification: "true".into(),
        acceptance_criteria: vec!["a".into()],
    };
    std::fs::write(run_dir.join("spec.json"), serde_json::to_string(&sp).unwrap()).unwrap();

    set_gate_at(&repo, &id, state::Gate::Spec, "again", true).unwrap();
    assert_eq!(status(&repo, &id), Status::Staged, "re-approving must not un-stage it");
    assert!(unstage_at(&repo, &id).is_ok(), "and unstage must still own it");

    // and a rejection cannot erase the record of a commit that exists
    stage_at(&repo, &id).unwrap();
    commit_at(&repo, &id, "add a", "").unwrap();
    set_gate_at(&repo, &id, state::Gate::Work, "changed my mind", false).unwrap();
    assert_eq!(status(&repo, &id), Status::Committed);
    std::fs::remove_dir_all(&repo).ok();
}

/// Staging applies both patches in one `git apply`, so a second one that
/// cannot apply leaves nothing behind. Applied separately, the first landed
/// in the user's index while the run still called itself `Reviewed`: guvnor
/// had changed the repo with no record that it had.
#[test]
fn a_patch_that_cannot_apply_leaves_the_tree_untouched() {
    let (repo, id) = fixture("half-apply");
    let run_dir = state::resolve_run_dir(&repo, &id).unwrap();
    // impl.patch now claims to edit a file that does not exist on base
    let broken = "diff --git a/src/ghost.js b/src/ghost.js\n\
                  --- a/src/ghost.js\n\
                  +++ b/src/ghost.js\n\
                  @@ -1 +1 @@\n\
                  -was here\n\
                  +is here\n";
    std::fs::write(run_dir.join("impl.patch"), broken).unwrap();
    let tests_patch = std::fs::read_to_string(run_dir.join("tests.patch")).unwrap();
    // keep the approvals and the verdict honest about the new pair
    let mut st = State::load(&run_dir).unwrap();
    st.gates.work.sha256 = digest::sha256_hex(broken.as_bytes());
    st.save(&run_dir).unwrap();
    let mut review: review::Review =
        serde_json::from_str(&std::fs::read_to_string(run_dir.join("review.json")).unwrap())
            .unwrap();
    review.diff_sha256 = digest::sha256_hex(combined(&tests_patch, broken).as_bytes());
    std::fs::write(run_dir.join("review.json"), serde_json::to_string(&review).unwrap())
        .unwrap();

    assert!(stage_at(&repo, &id).is_err(), "an unappliable patch must not stage");
    assert_eq!(
        git::git(&repo, &["status", "--porcelain"]).unwrap().trim(),
        "",
        "the tests half must not be left in the tree"
    );
    assert_eq!(status(&repo, &id), Status::Reviewed, "and the run keeps its status");
    std::fs::remove_dir_all(&repo).ok();
}

/// A re-run rewrites both patches AND the review.json that digests them, so
/// the combined check alone would wave the new diff through on yesterday's
/// ticks. Each gate binding to its own patch is what refuses it.
#[test]
fn a_rerun_cannot_inherit_the_previous_approvals() {
    let (repo, id) = fixture("rerun");
    let run_dir = state::resolve_run_dir(&repo, &id).unwrap();
    // Everything a fresh run leaves behind: two patches that are not the
    // approved ones, and a verdict whose digest matches them exactly. Both
    // still apply cleanly, so only the gate bindings can refuse them.
    let (tests, imp) = (
        std::fs::read_to_string(run_dir.join("impl.patch")).unwrap(),
        std::fs::read_to_string(run_dir.join("tests.patch")).unwrap(),
    );
    std::fs::write(run_dir.join("tests.patch"), &tests).unwrap();
    std::fs::write(run_dir.join("impl.patch"), &imp).unwrap();
    let mut review: review::Review =
        serde_json::from_str(&std::fs::read_to_string(run_dir.join("review.json")).unwrap())
            .unwrap();
    review.diff_sha256 = digest::sha256_hex(format!("{tests}\n{imp}").as_bytes());
    std::fs::write(run_dir.join("review.json"), serde_json::to_string(&review).unwrap())
        .unwrap();

    let e = stage_at(&repo, &id).unwrap_err().to_string();
    assert!(e.contains("tests.patch is not what the tests gate approved"), "{e}");
    assert!(e.contains("re-approve"), "must name the way out: {e}");
    // and nothing reached the tree behind the refusal
    assert_eq!(git::git(&repo, &["status", "--porcelain"]).unwrap().trim(), "");
    std::fs::remove_dir_all(&repo).ok();
}

/// The point of the whole change: staging stops, so you can look.
#[test]
fn staging_lands_in_your_tree_and_stops_there() {
    let (repo, id) = fixture("happy");
    let msg = stage_at(&repo, &id).unwrap();
    assert!(msg.contains("2 file(s)"), "{msg}");
    assert_eq!(status(&repo, &id), Status::Staged);
    // the files are really there, and readable with an editor
    assert_eq!(std::fs::read_to_string(repo.join("src/a.js")).unwrap(), "impl-ok\n");
    assert_eq!(std::fs::read_to_string(repo.join("test/a.test.js")).unwrap(), "test-ok\n");
    // ...and no commit was written
    let log = git::git(&repo, &["log", "--oneline"]).unwrap();
    assert_eq!(log.lines().count(), 1, "staging must not commit: {log}");
    // staging twice is not an error and does not double-apply
    assert!(stage_at(&repo, &id).unwrap().contains("already staged"));

    // then the commit, which is the one guvnor will sign
    let msg = commit_at(&repo, &id, "add a", "why").unwrap();
    assert!(msg.contains("committed"), "{msg}");
    assert_eq!(status(&repo, &id), Status::Committed);
    let log = git::git(&repo, &["log", "--oneline"]).unwrap();
    assert_eq!(log.lines().count(), 2, "exactly one commit: {log}");
    let body = git::git(&repo, &["log", "-1", "--pretty=%B"]).unwrap();
    assert!(body.contains("add a") && body.contains("why"), "{body}");
    assert_eq!(git::git(&repo, &["status", "--porcelain"]).unwrap().trim(), "");
    std::fs::remove_dir_all(&repo).ok();
}

/// An untracked scratch file is none of the patch's business, so it must not
/// dirty the tree for staging — same tolerance `write-tree` already gives it.
#[test]
fn an_untracked_file_does_not_block_staging() {
    let (repo, id) = fixture("untracked");
    std::fs::write(repo.join("scratch.txt"), "notes\n").unwrap();
    assert!(stage_at(&repo, &id).is_ok(), "untracked file must not block staging");
    assert_eq!(status(&repo, &id), Status::Staged);
    std::fs::remove_dir_all(&repo).ok();
}

/// Guvnor signs what a reviewer read. Once you have edited the staged
/// change it is your work, and both of guvnor's next moves refuse it.
#[test]
fn an_edited_staging_area_refuses_the_commit_and_the_unstage() {
    let (repo, id) = fixture("drift");
    stage_at(&repo, &id).unwrap();
    // your own edit, staged on top
    std::fs::write(repo.join("src/a.js"), "mine now\n").unwrap();
    git::git(&repo, &["add", "src/a.js"]).unwrap();

    for e in [
        commit_at(&repo, &id, "add a", "").unwrap_err(),
        unstage_at(&repo, &id).unwrap_err(),
        stage_at(&repo, &id).unwrap_err(),
    ] {
        let msg = format!("{e:#}");
        assert!(msg.contains("no longer the one that was reviewed"), "{msg}");
        assert!(msg.contains("git reset"), "must name the way out: {msg}");
    }
    // nothing was committed behind the refusal
    assert_eq!(git::git(&repo, &["log", "--oneline"]).unwrap().lines().count(), 1);
    assert_eq!(status(&repo, &id), Status::Staged);

    // an unstaged edit is only worth saying out loud: the index is still the
    // reviewed content, so a commit of the index is honest
    std::fs::write(repo.join("test/a.test.js"), "scribbled\n").unwrap();
    assert_eq!(unstaged_edits_at(&repo, &id).unwrap(), ["test/a.test.js"]);
    std::fs::remove_dir_all(&repo).ok();
}

/// Looked at it, didn't like it: the way back has to leave no trace in the
/// tree and no damage to the evidence.
#[test]
fn unstage_puts_the_tree_back_and_keeps_the_artifacts() {
    let (repo, id) = fixture("unstage");
    stage_at(&repo, &id).unwrap();
    let msg = unstage_at(&repo, &id).unwrap();
    assert!(msg.contains("back as it was"), "{msg}");
    assert_eq!(status(&repo, &id), Status::Reviewed, "and it can be fixed or staged again");
    // reversing a patch that CREATED files must remove them from the index
    // and from disk — a leftover file is a change you never asked for
    assert_eq!(git::git(&repo, &["status", "--porcelain"]).unwrap().trim(), "");
    assert!(!repo.join("src/a.js").exists());
    assert!(!repo.join("test/a.test.js").exists());
    // the evidence is untouched, so staging again works
    let run_dir = state::resolve_run_dir(&repo, &id).unwrap();
    assert!(run_dir.join("impl.patch").is_file() && run_dir.join("review.json").is_file());
    assert!(stage_at(&repo, &id).is_ok(), "must be re-stageable");
    std::fs::remove_dir_all(&repo).ok();
}
